from PyQt5.QtWidgets import QWidget, QGridLayout, QTableWidget, QGroupBox, QTabWidget, QTextEdit, QPushButton, QLabel, \
    QMenuBar, QSizePolicy, QAbstractItemView, QTableWidgetItem, QAbstractScrollArea, QHBoxLayout, QFrame, QMenu, \
    QStatusBar, QAction

from PyQt5.QtCore import QSize, QMetaObject, QRect, Qt, QCoreApplication

from PyQt5.QtGui import QFont, QCursor


class Ui_MainWindow(object):

    def __init__(self, MainWindow):
        self.centralwidget = QWidget(MainWindow)
        self.groupBox_2 = QGroupBox(self.centralwidget)
        self.gridLayout_4 = QGridLayout(self.groupBox_2)
        self.Registers_tab_2 = QWidget()
        self.Register_Contents_2 = QGroupBox(self.Registers_tab_2)
        self.RegisterContentWidget = QTableWidget(self.Register_Contents_2)
        self.tableWidget = QTableWidget(self.Register_Contents_2)
        self.groupBox_5 = QGroupBox(self.Registers_tab_2)
        self.FlagContentWidget = QTableWidget(self.groupBox_5)
        self.Memory_tab_2 = QWidget()
        self.groupBox = QGroupBox(self.centralwidget)
        self.tabWidget = QTabWidget(self.groupBox)
        self.tab = QWidget()
        self.gridLayout = QGridLayout(self.tab)
        self.textEdit = QTextEdit(self.tab)
        self.ExecuteButton = QPushButton(self.tab)
        self.AssembleButton = QPushButton(self.tab)
        self.tab_2 = QWidget()
        self.gridLayout_6 = QGridLayout(self.tab_2)
        self.StepExecBtn = QPushButton(self.tab_2)
        self.RunAllBtn = QPushButton(self.tab_2)
        self.MemHexTable = QTableWidget(self.tab_2)
        self.WarningLabel = QLabel(self.centralwidget)
        self.gridLayout_5 = QGridLayout(self.groupBox)
        self.menubar = QMenuBar(MainWindow)

    def setupSomeUi(self, SecondWindow):
        SecondWindow.resize(883,678)
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SecondWindow.sizePolicy().hasHeightForWidth())
        SecondWindow.setSizePolicy(sizePolicy)
        self.anotherwidget = QWidget(SecondWindow)
        self.chu = QPushButton(self.anotherwidget)
        self.chu.setMinimumSize(QSize(0, 48))
        self.grid = QGridLayout(self.anotherwidget)
        self.grid.addWidget(self.chu)
        QMetaObject.connectSlotsByName(SecondWindow)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(883, 678)
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)

        self.centralwidget.setObjectName("centralwidget")

        self.groupBox_2.setGeometry(QRect(535, 9, 330, 600))
        self.groupBox_2.setObjectName("groupBox_2")

        self.gridLayout_4.setObjectName("gridLayout_4")
        self.DisplayTab = QTabWidget(self.groupBox_2)

        font = QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)

        self.DisplayTab.setFont(font)
        self.DisplayTab.setCursor(QCursor(Qt.ArrowCursor))
        self.DisplayTab.setAutoFillBackground(False)
        self.DisplayTab.setTabShape(QTabWidget.Triangular)
        self.DisplayTab.setObjectName("DisplayTab")

        self.Registers_tab_2.setObjectName("Registers_tab_2")

        self.Register_Contents_2.setGeometry(QRect(9, 9, 286, 411))
        self.Register_Contents_2.setObjectName("Register_Contents_2")

        self.RegisterContentWidget.setGeometry(QRect(10, 20, 266, 200))
        self.RegisterContentWidget.setMaximumSize(QSize(281, 16777215))
        self.RegisterContentWidget.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.RegisterContentWidget.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.RegisterContentWidget.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.RegisterContentWidget.setObjectName("RegisterContentWidget")

        self.RegisterContentWidget.setColumnCount(2)
        self.RegisterContentWidget.setRowCount(8)

        item = QTableWidgetItem()
        self.RegisterContentWidget.setVerticalHeaderItem(0, item)
        item = QTableWidgetItem()
        self.RegisterContentWidget.setVerticalHeaderItem(1, item)
        item = QTableWidgetItem()
        self.RegisterContentWidget.setVerticalHeaderItem(2, item)
        item = QTableWidgetItem()
        self.RegisterContentWidget.setVerticalHeaderItem(3, item)
        item = QTableWidgetItem()
        self.RegisterContentWidget.setVerticalHeaderItem(4, item)
        item = QTableWidgetItem()
        self.RegisterContentWidget.setVerticalHeaderItem(5, item)
        item = QTableWidgetItem()
        self.RegisterContentWidget.setVerticalHeaderItem(6, item)
        item = QTableWidgetItem()
        self.RegisterContentWidget.setVerticalHeaderItem(7, item)
        item = QTableWidgetItem()
        self.RegisterContentWidget.setHorizontalHeaderItem(0, item)
        item = QTableWidgetItem()
        self.RegisterContentWidget.setHorizontalHeaderItem(1, item)
        item = QTableWidgetItem()
        self.RegisterContentWidget.setItem(0, 0, item)
        item = QTableWidgetItem()
        self.RegisterContentWidget.setItem(1, 0, item)
        item = QTableWidgetItem()
        self.RegisterContentWidget.setItem(2, 0, item)
        item = QTableWidgetItem()
        self.RegisterContentWidget.setItem(3, 0, item)
        item = QTableWidgetItem()
        self.RegisterContentWidget.setItem(4, 0, item)
        item = QTableWidgetItem()
        self.RegisterContentWidget.setItem(5, 0, item)
        item = QTableWidgetItem()
        self.RegisterContentWidget.setItem(6, 0, item)
        item = QTableWidgetItem()
        self.RegisterContentWidget.setItem(7, 0, item)

        self.RegisterContentWidget.horizontalHeader().setDefaultSectionSize(134)
        self.RegisterContentWidget.verticalHeader().setVisible(False)
        self.RegisterContentWidget.verticalHeader().setDefaultSectionSize(25)

        self.tableWidget.setGeometry(QRect(10, 231, 266, 171))
        self.tableWidget.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.tableWidget.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.tableWidget.setSizeAdjustPolicy(QAbstractScrollArea.AdjustToContents)
        self.tableWidget.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(5)
        item = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QTableWidgetItem()
        self.tableWidget.setItem(4, 0, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(134)
        self.tableWidget.verticalHeader().setVisible(False)

        self.groupBox_5.setGeometry(QRect(9, 426, 286, 105))
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_2 = QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")


        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.FlagContentWidget.sizePolicy().hasHeightForWidth())
        self.FlagContentWidget.setSizePolicy(sizePolicy)

        self.FlagContentWidget.setMinimumSize(QSize(266, 55))
        # self.FlagContentWidget.setMaximumSize(.QSize(266, 55))
        self.FlagContentWidget.setSizeIncrement(QSize(0, 30))
        self.FlagContentWidget.setBaseSize(QSize(266, 59))

        self.FlagContentWidget.setInputMethodHints(Qt.ImhNone)
        self.FlagContentWidget.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.FlagContentWidget.setObjectName("FlagContentWidget")
        self.FlagContentWidget.setColumnCount(8)
        self.FlagContentWidget.setRowCount(1)

        # Initializing Items of Flag Table
        item = QTableWidgetItem()
        self.FlagContentWidget.setVerticalHeaderItem(0, item)
        item = QTableWidgetItem()
        self.FlagContentWidget.setHorizontalHeaderItem(0, item)
        item = QTableWidgetItem()
        self.FlagContentWidget.setHorizontalHeaderItem(1, item)
        item = QTableWidgetItem()
        self.FlagContentWidget.setHorizontalHeaderItem(2, item)
        item = QTableWidgetItem()
        self.FlagContentWidget.setHorizontalHeaderItem(3, item)
        item = QTableWidgetItem()
        self.FlagContentWidget.setHorizontalHeaderItem(4, item)
        item = QTableWidgetItem()
        self.FlagContentWidget.setHorizontalHeaderItem(5, item)
        item = QTableWidgetItem()
        self.FlagContentWidget.setHorizontalHeaderItem(6, item)
        item = QTableWidgetItem()
        self.FlagContentWidget.setHorizontalHeaderItem(7, item)
        self.FlagContentWidget.horizontalHeader().setDefaultSectionSize(15)
        self.FlagContentWidget.verticalHeader().setVisible(False)
        self.FlagContentWidget.verticalHeader().setDefaultSectionSize(30)
        self.FlagContentWidget.verticalHeader().setHighlightSections(True)
        self.horizontalLayout_2.addWidget(self.FlagContentWidget)

        self.DisplayTab.addTab(self.Registers_tab_2, "")

        self.Memory_tab_2.setObjectName("Memory_tab_2")
        self.Memory_Widget = QTableWidget(self.Memory_tab_2)
        self.Memory_Widget.setGeometry(QRect(2, 0, 299, 561))
        self.Memory_Widget.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.Memory_Widget.setSizeAdjustPolicy(QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.Memory_Widget.setObjectName("Memory_Widget")
        self.Memory_Widget.setColumnCount(2)
        self.Memory_Widget.setRowCount(60)

        item = QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(0, item)
        item = QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(1, item)
        item = QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(2, item)
        item = QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(3, item)
        item = QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(4, item)
        item = QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(5, item)
        item = QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(6, item)
        item = QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(7, item)
        item = QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(8, item)
        item = QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(9, item)
        item = QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(10, item)
        item = QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(11, item)
        item = QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(12, item)
        item = QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(13, item)
        item = QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(14, item)
        item = QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(15, item)
        item = QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(16, item)
        item = QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(17, item)
        item = QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(18, item)
        item = QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(19, item)
        item = QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(20, item)
        item = QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(21, item)
        item = QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(22, item)
        item = QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(23, item)
        item = QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(24, item)
        item = QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(25, item)
        item = QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(26, item)
        item = QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(27, item)
        item = QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(28, item)
        item = QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(29, item)
        item = QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(30, item)
        item = QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(31, item)
        item = QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(32, item)
        item = QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(33, item)
        item = QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(34, item)
        item = QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(35, item)
        item = QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(36, item)
        item = QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(37, item)
        item = QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(38, item)
        item = QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(39, item)
        item = QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(40, item)
        item = QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(41, item)
        item = QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(42, item)
        item = QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(43, item)
        item = QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(44, item)
        item = QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(45, item)
        item = QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(46, item)
        item = QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(47, item)
        item = QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(48, item)
        item = QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(49, item)
        item = QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(50, item)
        item = QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(51, item)
        item = QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(52, item)
        item = QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(53, item)
        item = QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(54, item)
        item = QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(55, item)
        item = QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(56, item)
        item = QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(57, item)
        item = QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(58, item)
        item = QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(59, item)
        item = QTableWidgetItem()

        self.Memory_Widget.setHorizontalHeaderItem(0, item)
        item = QTableWidgetItem()
        self.Memory_Widget.setHorizontalHeaderItem(1, item)
        self.Memory_Widget.horizontalHeader().setDefaultSectionSize(147)
        self.Memory_Widget.verticalHeader().setVisible(False)
        self.Memory_Widget.verticalHeader().setHighlightSections(True)

        self.DisplayTab.addTab(self.Memory_tab_2, "")
        self.gridLayout_4.addWidget(self.DisplayTab, 0, 0, 1, 1)

        self.groupBox.setGeometry(QRect(9, 9, 511, 600))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_5.setObjectName("gridLayout_5")

        self.tabWidget.setEnabled(True)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setObjectName("tabWidget")

        self.tab.setObjectName("tab")

        self.gridLayout.setObjectName("gridLayout")

        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 0, 0, 1, 2)

        self.ExecuteButton.setMinimumSize(QSize(0, 48))
        self.ExecuteButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.ExecuteButton, 1, 0, 1, 1)

        self.AssembleButton.setMinimumSize(QSize(0, 48))
        self.AssembleButton.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.AssembleButton, 1, 1, 1, 1)

        self.tabWidget.addTab(self.tab, "")

        self.tab_2.setObjectName("tab_2")

        self.gridLayout_6.setObjectName("gridLayout_6")

        self.StepExecBtn.setMinimumSize(QSize(0, 48))
        self.StepExecBtn.setObjectName("StepExecBtn")
        self.gridLayout_6.addWidget(self.StepExecBtn, 1, 1, 1, 1)
        self.RunAllBtn.setMinimumSize(QSize(0, 48))
        self.RunAllBtn.setObjectName("RunAllBtn")
        self.gridLayout_6.addWidget(self.RunAllBtn, 1, 0, 1, 1)

        self.MemHexTable.setFrameShape(QFrame.Box)
        self.MemHexTable.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.MemHexTable.setSizeAdjustPolicy(QAbstractScrollArea.AdjustToContents)
        self.MemHexTable.setAutoScrollMargin(16)
        self.MemHexTable.setEditTriggers(QAbstractItemView.DoubleClicked)
        self.MemHexTable.setSelectionMode(QAbstractItemView.ExtendedSelection)
        self.MemHexTable.setSelectionBehavior(QAbstractItemView.SelectItems)
        self.MemHexTable.setIconSize(QSize(0, 0))
        self.MemHexTable.setRowCount(15)
        self.MemHexTable.setColumnCount(7)
        self.MemHexTable.setObjectName("MemHexTable")
        item = QTableWidgetItem()
        self.MemHexTable.setHorizontalHeaderItem(0, item)
        item = QTableWidgetItem()
        self.MemHexTable.setHorizontalHeaderItem(1, item)
        item = QTableWidgetItem()
        self.MemHexTable.setHorizontalHeaderItem(2, item)
        item = QTableWidgetItem()
        self.MemHexTable.setHorizontalHeaderItem(3, item)
        item = QTableWidgetItem()
        self.MemHexTable.setHorizontalHeaderItem(4, item)
        item = QTableWidgetItem()
        self.MemHexTable.setHorizontalHeaderItem(5, item)
        item = QTableWidgetItem()
        self.MemHexTable.setHorizontalHeaderItem(6, item)
        item = QTableWidgetItem()
        self.MemHexTable.setItem(0, 0, item)
        item = QTableWidgetItem()
        self.MemHexTable.setItem(0, 1, item)
        item = QTableWidgetItem()
        self.MemHexTable.setItem(1, 0, item)
        item = QTableWidgetItem()
        self.MemHexTable.setItem(1, 2, item)
        self.MemHexTable.horizontalHeader().setCascadingSectionResizes(False)
        self.MemHexTable.horizontalHeader().setDefaultSectionSize(65)
        self.MemHexTable.horizontalHeader().setHighlightSections(True)
        self.MemHexTable.horizontalHeader().setSortIndicatorShown(False)
        self.MemHexTable.horizontalHeader().setStretchLastSection(False)
        self.MemHexTable.verticalHeader().setVisible(False)
        self.MemHexTable.verticalHeader().setCascadingSectionResizes(False)
        self.MemHexTable.verticalHeader().setDefaultSectionSize(30)
        self.MemHexTable.verticalHeader().setMinimumSectionSize(21)
        self.gridLayout_6.addWidget(self.MemHexTable, 0, 0, 1, 2)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_5.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.WarningLabel.setGeometry(QRect(15, 615, 376, 20))

        MainWindow.setCentralWidget(self.centralwidget)

        self.menubar.setGeometry(QRect(0, 0, 883, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuSettings = QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionClose = QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionUndo = QAction(MainWindow)
        self.actionUndo.setObjectName("actionUndo")
        self.actionRedo = QAction(MainWindow)
        self.actionRedo.setObjectName("actionRedo")
        self.actionCut = QAction(MainWindow)
        self.actionCut.setObjectName("actionCut")
        self.actionCopy = QAction(MainWindow)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste = QAction(MainWindow)
        self.actionPaste.setObjectName("actionPaste")
        self.actionDelete = QAction(MainWindow)
        self.actionDelete.setObjectName("actionDelete")
        self.actionSelect_All = QAction(MainWindow)
        self.actionSelect_All.setObjectName("actionSelect_All")
        self.actionPreferences = QAction(MainWindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionClose)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addAction(self.actionDelete)
        self.menuEdit.addAction(self.actionSelect_All)
        self.menuSettings.addAction(self.actionPreferences)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        self.DisplayTab.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(1)
        QMetaObject.connectSlotsByName(MainWindow)

        # MainWindow.setTabOrder(self.DisplayTab, self.MemHexTable)
        # MainWindow.setTabOrder(self.MemHexTable, self.Memory_Widget)
        # MainWindow.setTabOrder(self.Memory_Widget, self.pushButton_2)
        # MainWindow.setTabOrder(self.pushButton_2, self.RunAllBtn)
        # MainWindow.setTabOrder(self.RunAllBtn, self.StepExecBtn)
        # MainWindow.setTabOrder(self.StepExecBtn, self.textEdit)
        # MainWindow.setTabOrder(self.textEdit, self.pushButton)
        # MainWindow.setTabOrder(self.pushButton, self.FlagContentWidget)
        # MainWindow.setTabOrder(self.FlagContentWidget, self.tabWidget)
        # MainWindow.setTabOrder(self.tabWidget, self.RegisterContentWidget)

    def retranslateUi(self, MainWindow):
        _translate = QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_2.setTitle(_translate("MainWindow", "GroupBox"))
        self.Register_Contents_2.setTitle(_translate("MainWindow", "Register Contents"))
        item = self.RegisterContentWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.RegisterContentWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.RegisterContentWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.RegisterContentWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.RegisterContentWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.RegisterContentWidget.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.RegisterContentWidget.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.RegisterContentWidget.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.RegisterContentWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Registers"))
        item = self.RegisterContentWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Value"))
        __sortingEnabled = self.RegisterContentWidget.isSortingEnabled()
        self.RegisterContentWidget.setSortingEnabled(False)
        item = self.RegisterContentWidget.item(0, 0)
        item.setText(_translate("MainWindow", "Accumulator(A)"))
        item = self.RegisterContentWidget.item(1, 0)
        item.setText(_translate("MainWindow", "Register B"))
        item = self.RegisterContentWidget.item(2, 0)
        item.setText(_translate("MainWindow", "Register C"))
        item = self.RegisterContentWidget.item(3, 0)
        item.setText(_translate("MainWindow", "Register D"))
        item = self.RegisterContentWidget.item(4, 0)
        item.setText(_translate("MainWindow", "Register E"))
        item = self.RegisterContentWidget.item(5, 0)
        item.setText(_translate("MainWindow", "Register H"))
        item = self.RegisterContentWidget.item(6, 0)
        item.setText(_translate("MainWindow", "Register L"))
        item = self.RegisterContentWidget.item(7, 0)
        item.setText(_translate("MainWindow", "Register M"))
        self.RegisterContentWidget.setSortingEnabled(__sortingEnabled)
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Register Pairs"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Value"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "PSW"))
        item.setToolTip(_translate("MainWindow", "Program Staus Word"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("MainWindow", "BC"))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("MainWindow", "DE"))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("MainWindow", "HL"))
        item = self.tableWidget.item(4, 0)
        item.setText(_translate("MainWindow", "Stack Pointer"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.groupBox_5.setTitle(_translate("MainWindow", "Flags"))
        item = self.FlagContentWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.FlagContentWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "S"))
        item = self.FlagContentWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Z"))
        item = self.FlagContentWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "*"))
        item = self.FlagContentWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "AC"))
        item = self.FlagContentWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "*"))
        item = self.FlagContentWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "PC"))
        item = self.FlagContentWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "*"))
        item = self.FlagContentWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "CY"))
        self.DisplayTab.setTabText(self.DisplayTab.indexOf(self.Registers_tab_2), _translate("MainWindow", "Registers"))
        item = self.Memory_Widget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(13)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(14)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(15)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(16)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(17)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(18)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(19)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(20)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(21)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(22)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(23)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(24)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(25)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(26)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(27)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(28)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(29)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(30)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(31)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(32)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(33)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(34)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(35)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(36)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(37)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(38)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(39)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(40)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(41)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(42)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(43)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(44)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(45)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(46)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(47)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(48)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(49)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(50)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(51)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(52)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(53)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(54)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(55)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(56)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(57)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(58)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(59)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Mem. Address"))
        item = self.Memory_Widget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Value"))
        self.DisplayTab.setTabText(self.DisplayTab.indexOf(self.Memory_tab_2), _translate("MainWindow", "Memory"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.ExecuteButton.setText(_translate("MainWindow", "Execute"))
        self.AssembleButton.setText(_translate("MainWindow", "Assemble"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Editor"))
        self.StepExecBtn.setText(_translate("MainWindow", "Step By Step"))
        self.RunAllBtn.setText(_translate("MainWindow", "Run Whole"))
        item = self.MemHexTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Address"))
        item = self.MemHexTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Label"))
        item = self.MemHexTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Mnemonics"))
        item = self.MemHexTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Hex Code"))
        item = self.MemHexTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Bytes"))
        item = self.MemHexTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "M-cycles"))
        item = self.MemHexTable.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "T-States"))
        __sortingEnabled = self.MemHexTable.isSortingEnabled()
        self.MemHexTable.setSortingEnabled(False)
        self.MemHexTable.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Assembler"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionUndo.setText(_translate("MainWindow", "Undo"))
        self.actionUndo.setShortcut(_translate("MainWindow", "Ctrl+Z"))
        self.actionRedo.setText(_translate("MainWindow", "Redo"))
        self.actionRedo.setShortcut(_translate("MainWindow", "Ctrl+Y"))
        self.actionCut.setText(_translate("MainWindow", "Cut"))
        self.actionCut.setShortcut(_translate("MainWindow", "Ctrl+X"))
        self.actionCopy.setText(_translate("MainWindow", "Copy"))
        self.actionCopy.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.actionPaste.setText(_translate("MainWindow", "Paste"))
        self.actionPaste.setShortcut(_translate("MainWindow", "Ctrl+V"))
        self.actionDelete.setText(_translate("MainWindow", "Delete"))
        self.actionSelect_All.setText(_translate("MainWindow", "Select All"))
        self.actionSelect_All.setShortcut(_translate("MainWindow", "Ctrl+A"))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences"))
        self.actionPreferences.setShortcut(_translate("MainWindow", "Alt+P"))

