# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LatestUI.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):

    def __init__(self, MainWindow):
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.tabWidget = QtWidgets.QTabWidget(self.groupBox)
        self.Editor_tab = QtWidgets.QWidget()
        self.AssembleBtn = QtWidgets.QPushButton(self.Editor_tab)
        self.CorrectBtn = QtWidgets.QPushButton(self.Editor_tab)
        self.textEdit = QtWidgets.QTextEdit(self.Editor_tab)
        self.Assembler_tab = QtWidgets.QWidget()
        self.groupBox_3 = QtWidgets.QGroupBox(self.Assembler_tab)
        self.tab_2 = QtWidgets.QWidget()
        self.RunAllBtn = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_2 = QtWidgets.QPushButton(self.Assembler_tab)
        self.MemHexTable = QtWidgets.QTableWidget(self.Assembler_tab)

        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.DisplayTab = QtWidgets.QTabWidget(self.groupBox_2)
        self.Registers_tab = QtWidgets.QWidget()
        self.Register_Contents = QtWidgets.QGroupBox(self.Registers_tab)
        self.RegisterContentWidget = QtWidgets.QTableWidget(self.Register_Contents)
        self.groupBox_4 = QtWidgets.QGroupBox(self.Register_Contents)
        self.FlagContentWidget = QtWidgets.QTableWidget(self.groupBox_4)
        self.Memory_tab = QtWidgets.QWidget()
        self.Memory_Widget = QtWidgets.QTableWidget(self.Memory_tab)
        self.menubar = QtWidgets.QMenuBar(MainWindow)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(883, 678)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.DisplayTab = QtWidgets.QTabWidget(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.DisplayTab.setFont(font)
        self.DisplayTab.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.DisplayTab.setAutoFillBackground(False)
        self.DisplayTab.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.DisplayTab.setObjectName("DisplayTab")
        self.Registers_tab_2 = QtWidgets.QWidget()
        self.Registers_tab_2.setObjectName("Registers_tab_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.Registers_tab_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.Register_Contents_2 = QtWidgets.QGroupBox(self.Registers_tab_2)
        self.Register_Contents_2.setObjectName("Register_Contents_2")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.Register_Contents_2)
        self.gridLayout_7.setObjectName("gridLayout_7")

        self.RegisterContentWidget = QtWidgets.QTableWidget(self.Register_Contents_2)
        self.RegisterContentWidget.setMaximumSize(QtCore.QSize(281, 16777215))
        self.RegisterContentWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.RegisterContentWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.RegisterContentWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.RegisterContentWidget.setObjectName("RegisterContentWidget")
        self.RegisterContentWidget.setColumnCount(2)
        self.RegisterContentWidget.setRowCount(8)
        item = QtWidgets.QTableWidgetItem()
        self.RegisterContentWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.RegisterContentWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.RegisterContentWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.RegisterContentWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.RegisterContentWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.RegisterContentWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.RegisterContentWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.RegisterContentWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.RegisterContentWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.RegisterContentWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.RegisterContentWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.RegisterContentWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.RegisterContentWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.RegisterContentWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.RegisterContentWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.RegisterContentWidget.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.RegisterContentWidget.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.RegisterContentWidget.setItem(7, 0, item)
        self.RegisterContentWidget.horizontalHeader().setDefaultSectionSize(139)
        self.RegisterContentWidget.verticalHeader().setVisible(False)
        self.RegisterContentWidget.verticalHeader().setDefaultSectionSize(25)
        self.gridLayout_7.addWidget(self.RegisterContentWidget, 0, 0, 1, 1)

        self.RegisterPairWidget = QtWidgets.QTableWidget(self.Register_Contents_2)
        self.RegisterPairWidget.setMinimumSize(QtCore.QSize(202, 175))
        self.RegisterPairWidget.setMaximumSize(QtCore.QSize(281, 171))
        self.RegisterPairWidget.setAutoFillBackground(False)
        self.RegisterPairWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.RegisterPairWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.RegisterPairWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.RegisterPairWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.RegisterPairWidget.setIconSize(QtCore.QSize(0, 0))
        self.RegisterPairWidget.setTextElideMode(QtCore.Qt.ElideRight)
        self.RegisterPairWidget.setObjectName("RegisterPairWidget")
        self.RegisterPairWidget.setColumnCount(2)
        self.RegisterPairWidget.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.RegisterPairWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.RegisterPairWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.RegisterPairWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.RegisterPairWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.RegisterPairWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.RegisterPairWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.RegisterPairWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.RegisterPairWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.RegisterPairWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.RegisterPairWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.RegisterPairWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.RegisterPairWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.RegisterPairWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.RegisterPairWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.RegisterPairWidget.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.RegisterPairWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.RegisterPairWidget.setItem(4, 1, item)
        self.RegisterPairWidget.horizontalHeader().setDefaultSectionSize(139)
        self.RegisterPairWidget.horizontalHeader().setVisible(True)
        self.RegisterPairWidget.verticalHeader().setVisible(False)
        self.gridLayout_7.addWidget(self.RegisterPairWidget, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.Register_Contents_2, 0, 0, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.Registers_tab_2)
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.FlagContentWidget = QtWidgets.QTableWidget(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FlagContentWidget.sizePolicy().hasHeightForWidth())
        self.FlagContentWidget.setSizePolicy(sizePolicy)
        self.FlagContentWidget.setMinimumSize(QtCore.QSize(270, 55))
        self.FlagContentWidget.setMaximumSize(QtCore.QSize(266, 55))
        self.FlagContentWidget.setSizeIncrement(QtCore.QSize(0, 40))
        self.FlagContentWidget.setBaseSize(QtCore.QSize(266, 55))
        self.FlagContentWidget.setInputMethodHints(QtCore.Qt.ImhNone)

        self.FlagContentWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.FlagContentWidget.setObjectName("FlagContentWidget")
        self.FlagContentWidget.setColumnCount(8)
        self.FlagContentWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.FlagContentWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.FlagContentWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.FlagContentWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.FlagContentWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.FlagContentWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.FlagContentWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.FlagContentWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.FlagContentWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.FlagContentWidget.setHorizontalHeaderItem(7, item)
        self.FlagContentWidget.horizontalHeader().setDefaultSectionSize(20)
        self.FlagContentWidget.horizontalHeader().setDefaultSectionSize(17)
        self.FlagContentWidget.verticalHeader().setVisible(False)
        self.FlagContentWidget.verticalHeader().setHighlightSections(True)
        self.horizontalLayout_2.addWidget(self.FlagContentWidget)
        self.gridLayout_3.addWidget(self.groupBox_5, 2, 0, 1, 1)
        self.DisplayTab.addTab(self.Registers_tab_2, "")
        self.Memory_tab_2 = QtWidgets.QWidget()
        self.Memory_tab_2.setObjectName("Memory_tab_2")
        self.Memory_Widget = QtWidgets.QTableWidget(self.Memory_tab_2)
        self.Memory_Widget.setGeometry(QtCore.QRect(0, 0, 307, 561))
        self.Memory_Widget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Memory_Widget.setObjectName("Memory_Widget")
        self.Memory_Widget.setColumnCount(2)
        self.Memory_Widget.setRowCount(60)
        item = QtWidgets.QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(23, item)
        item = QtWidgets.QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(24, item)
        item = QtWidgets.QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(25, item)
        item = QtWidgets.QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(26, item)
        item = QtWidgets.QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(27, item)
        item = QtWidgets.QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(28, item)
        item = QtWidgets.QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(29, item)
        item = QtWidgets.QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(30, item)
        item = QtWidgets.QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(31, item)
        item = QtWidgets.QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(32, item)
        item = QtWidgets.QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(33, item)
        item = QtWidgets.QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(34, item)
        item = QtWidgets.QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(35, item)
        item = QtWidgets.QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(36, item)
        item = QtWidgets.QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(37, item)
        item = QtWidgets.QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(38, item)
        item = QtWidgets.QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(39, item)
        item = QtWidgets.QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(40, item)
        item = QtWidgets.QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(41, item)
        item = QtWidgets.QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(42, item)
        item = QtWidgets.QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(43, item)
        item = QtWidgets.QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(44, item)
        item = QtWidgets.QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(45, item)
        item = QtWidgets.QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(46, item)
        item = QtWidgets.QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(47, item)
        item = QtWidgets.QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(48, item)
        item = QtWidgets.QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(49, item)
        item = QtWidgets.QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(50, item)
        item = QtWidgets.QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(51, item)
        item = QtWidgets.QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(52, item)
        item = QtWidgets.QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(53, item)
        item = QtWidgets.QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(54, item)
        item = QtWidgets.QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(55, item)
        item = QtWidgets.QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(56, item)
        item = QtWidgets.QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(57, item)
        item = QtWidgets.QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(58, item)
        item = QtWidgets.QTableWidgetItem()
        self.Memory_Widget.setVerticalHeaderItem(59, item)
        item = QtWidgets.QTableWidgetItem()
        self.Memory_Widget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Memory_Widget.setHorizontalHeaderItem(1, item)
        self.Memory_Widget.horizontalHeader().setDefaultSectionSize(147)
        self.Memory_Widget.verticalHeader().setVisible(False)
        self.Memory_Widget.verticalHeader().setHighlightSections(True)
        self.DisplayTab.addTab(self.Memory_tab_2, "")
        self.gridLayout_4.addWidget(self.DisplayTab, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.tabWidget = QtWidgets.QTabWidget(self.groupBox)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        self.textEdit = QtWidgets.QTextEdit(self.tab)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 0, 0, 1, 2)
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 48))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 48))
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.MemHexTable = QtWidgets.QTableWidget(self.tab_2)
        self.MemHexTable.setFrameShape(QtWidgets.QFrame.Box)
        self.MemHexTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.MemHexTable.setAutoScrollMargin(16)
        self.MemHexTable.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
        self.MemHexTable.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.MemHexTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.MemHexTable.setIconSize(QtCore.QSize(0, 0))
        self.MemHexTable.setRowCount(15)
        self.MemHexTable.setColumnCount(4)
        self.MemHexTable.setObjectName("MemHexTable")
        item = QtWidgets.QTableWidgetItem()
        self.MemHexTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.MemHexTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.MemHexTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.MemHexTable.setHorizontalHeaderItem(3, item)

        item = QtWidgets.QTableWidgetItem()
        self.MemHexTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.MemHexTable.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.MemHexTable.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.MemHexTable.setItem(1, 2, item)
        self.MemHexTable.horizontalHeader().setCascadingSectionResizes(False)
        self.MemHexTable.horizontalHeader().setDefaultSectionSize(118)
        self.MemHexTable.horizontalHeader().setHighlightSections(True)
        self.MemHexTable.horizontalHeader().setSortIndicatorShown(False)
        self.MemHexTable.horizontalHeader().setStretchLastSection(False)
        self.MemHexTable.verticalHeader().setVisible(False)
        self.MemHexTable.verticalHeader().setCascadingSectionResizes(False)
        self.MemHexTable.verticalHeader().setDefaultSectionSize(30)
        self.MemHexTable.verticalHeader().setMinimumSectionSize(21)

        self.gridLayout_6.addWidget(self.MemHexTable, 0, 0, 1, 2)
        self.RunAllBtn = QtWidgets.QPushButton(self.tab_2)
        self.RunAllBtn.setMinimumSize(QtCore.QSize(0, 48))
        self.RunAllBtn.setObjectName("RunAllBtn")
        self.gridLayout_6.addWidget(self.RunAllBtn, 1, 0, 1, 1)
        self.StepExecBtn = QtWidgets.QPushButton(self.tab_2)
        self.StepExecBtn.setMinimumSize(QtCore.QSize(0, 48))
        self.StepExecBtn.setObjectName("StepExecBtn")
        self.gridLayout_6.addWidget(self.StepExecBtn, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_5.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 883, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.DisplayTab.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_2.setTitle(_translate("MainWindow", "GroupBox"))
        self.Register_Contents_2.setTitle(_translate("MainWindow", "Register Contents"))
        item = self.RegisterContentWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.RegisterContentWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.RegisterContentWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.RegisterContentWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.RegisterContentWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.RegisterContentWidget.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.RegisterContentWidget.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.RegisterContentWidget.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.RegisterContentWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Registers"))
        item = self.RegisterContentWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Value"))
        __sortingEnabled = self.RegisterContentWidget.isSortingEnabled()
        self.RegisterContentWidget.setSortingEnabled(False)
        item = self.RegisterContentWidget.item(0, 0)
        item.setText(_translate("MainWindow", "Accumulator(A)"))
        item = self.RegisterContentWidget.item(1, 0)
        item.setText(_translate("MainWindow", "Register B"))
        item = self.RegisterContentWidget.item(2, 0)
        item.setText(_translate("MainWindow", "Register C"))
        item = self.RegisterContentWidget.item(3, 0)
        item.setText(_translate("MainWindow", "Register D"))
        item = self.RegisterContentWidget.item(4, 0)
        item.setText(_translate("MainWindow", "Register E"))
        item = self.RegisterContentWidget.item(5, 0)
        item.setText(_translate("MainWindow", "Register H"))
        item = self.RegisterContentWidget.item(6, 0)
        item.setText(_translate("MainWindow", "Register L"))
        item = self.RegisterContentWidget.item(7, 0)
        item.setText(_translate("MainWindow", "Register M"))
        self.RegisterContentWidget.setSortingEnabled(__sortingEnabled)
        item = self.RegisterPairWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.RegisterPairWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.RegisterPairWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.RegisterPairWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.RegisterPairWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.RegisterPairWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Register Pairs"))
        item = self.RegisterPairWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Values"))
        __sortingEnabled = self.RegisterPairWidget.isSortingEnabled()
        self.RegisterPairWidget.setSortingEnabled(False)
        item = self.RegisterPairWidget.item(0, 0)
        item.setText(_translate("MainWindow", "Program Status Word"))
        item = self.RegisterPairWidget.item(1, 0)
        item.setText(_translate("MainWindow", "Register Pair BC"))
        item = self.RegisterPairWidget.item(2, 0)
        item.setText(_translate("MainWindow", "Register Pair DE"))
        item = self.RegisterPairWidget.item(3, 0)
        item.setText(_translate("MainWindow", "Register Pair HL"))
        item = self.RegisterPairWidget.item(4, 0)
        item.setText(_translate("MainWindow", "Stack Pointer"))
        self.RegisterPairWidget.setSortingEnabled(__sortingEnabled)
        self.groupBox_5.setTitle(_translate("MainWindow", "Flags"))
        item = self.FlagContentWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.FlagContentWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "S"))
        item = self.FlagContentWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Z"))
        item = self.FlagContentWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "*"))
        item = self.FlagContentWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "AC"))
        item = self.FlagContentWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "*"))
        item = self.FlagContentWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "PC"))
        item = self.FlagContentWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "*"))
        item = self.FlagContentWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "CY"))
        self.DisplayTab.setTabText(self.DisplayTab.indexOf(self.Registers_tab_2), _translate("MainWindow", "Registers"))
        item = self.Memory_Widget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(13)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(14)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(15)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(16)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(17)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(18)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(19)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(20)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(21)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(22)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(23)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(24)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(25)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(26)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(27)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(28)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(29)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(30)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(31)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(32)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(33)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(34)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(35)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(36)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(37)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(38)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(39)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(40)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(41)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(42)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(43)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(44)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(45)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(46)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(47)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(48)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(49)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(50)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(51)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(52)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(53)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(54)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(55)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(56)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(57)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(58)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.verticalHeaderItem(59)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.Memory_Widget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Mem. Address"))
        item = self.Memory_Widget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Value"))
        self.DisplayTab.setTabText(self.DisplayTab.indexOf(self.Memory_tab_2), _translate("MainWindow", "Memory"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.pushButton.setText(_translate("MainWindow", "Execute"))
        self.pushButton_2.setText(_translate("MainWindow", "Assemble"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Editor"))
        item = self.MemHexTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Address"))
        item = self.MemHexTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Label"))
        item = self.MemHexTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Mnemonics"))
        item = self.MemHexTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Hex Code"))

        __sortingEnabled = self.MemHexTable.isSortingEnabled()
        self.MemHexTable.setSortingEnabled(False)
        self.MemHexTable.setSortingEnabled(__sortingEnabled)
        self.RunAllBtn.setText(_translate("MainWindow", "Run Whole"))
        self.StepExecBtn.setText(_translate("MainWindow", "Step By Step"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Assembler"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow(MainWindow)
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
